---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
      shell: LC_ALL=en_US.utf-8 

    - name: pull docker image
      shell: docker pull tripathiharsh9/devops_pro

    - name: running container
      shell: docker run -it -d tripathiharsh9/devops_pro /bin/bash
